services:
  asset-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asset-app
    ports:
      - "127.0.0.1:8088:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./export_backups:/app/export_backups
    restart: unless-stopped
